/* fonts */
export const FontFamily = {
  poppinsSemibold: "Poppins_semibold",
  sFProTextSemibold: "SF Pro Text_semibold",
  poppinsMedium: "Poppins_medium",
  b1: "Poppins_regular",
  sFProDisplayLight: "SF Pro Display_light",
  manropeSemibold: "Manrope_semibold",
  outfitSemibold: "Outfit_semibold",
  outfitRegular: "Outfit_regular",
  poppinsBold: "Poppins_bold",
  sFProDisplaySemibold: "SF Pro Display_semibold",
  tittleLargeBold: "Raleway_bold",
  caption1Regular: "DM Sans_regular",
  calloutBold: "DM Sans_bold",
  sFProLight: "SF Pro_light",
  latoBold: "Lato_bold",
  interMedium: "Inter_medium",
  interSemibold: "Inter_semibold",
  interRegular: "Inter_regular",
  bodySemiBold: "DM Sans_medium",
  ralewayMedium: "Raleway_medium",
  questrialRegular: "Questrial_regular",
  headlineRegular: "Raleway_regular",
  nunitoRegular: "Nunito_regular",
  nunitoBold: "Nunito_bold",
  caption12pxRegular: "Roboto_regular",
  princessSofiaRegular: "Princess Sofia_regular",
};
/* font sizes */
export const FontSize = {
  size_6xs: 8,
  size_5xs: 10,
  size_4xs: 11,
  caption12pxRegular_size: 12,
  size_2xs: 13,
  bodySemiBold_size: 14,
  size_sm: 15,
  b1_size: 16,
  headlineRegular_size: 17,
  size_xl: 18,
  size_2xl: 20,
  size_3xl: 22,
  size_4xl: 23,
  tittleLargeBold_size: 24,
  size_6xl: 25,
};
/* Colors */
export const Color = {
  darkgray_100: "#999ea1",
  darkgray_200: "#979797",
  systemBackgroundSecondary: "#fcfcfc",
  white: "#fafafa",
  labelsColorsSecondary: "#8a8a8e",
  gray_400: "#838383",
  gray_500: "#2b2b2b",
  gray_600: "#242a31",
  black: "#141414",
  gray_800: "#0c0b0b",
  placeHolder: "rgba(31, 31, 31, 0.43)",
  whitesmoke_100: "#f4f4f4",
  darkslateblue_100: "#282460",
  darkslateblue_200: "#00214e",
  baseColorWhite: "#fff",
  labelscolorsPrimary: "#000",
  darkslategray_100: "#244025",
  darkGreen: "#033525",
  purpleSolid: "#4e0189",
  dimgray_100: "#626262",
  gray: "#565656",
  labelsColorsTertiary: "#c5c5c7",
  green: "#339f00",
  primary: "#046da8",
  royalblue: "#005de8",
  maroon: "#581a1a",
  olive: "#807300",
  systemTint5825E6: "#0f9aff",
  mediumspringgreen: "#13d377",
  mintcream: "#ebfaf5",
  gainsboro_100: "#e6e6e6",
  gainsboro_200: "#e0dede",
  firebrick: "#b02929",
  mistyrose: "#ffdfdf",
  mediumseagreen: "#549e4d",
};
/* Paddings */
export const Padding = {
  p_2xs: 8,
  p_xs: 12,
  p_sm: 13,
  p_md: 16,
  p_lg: 24,
  p_xl: 56,
  p_2xl: 129,
};
/* Margins */
export const Margin = {
  m_sm: 0,
  m_md: 3,
  m_lg: 12,
};
/* border radiuses */
export const Border = {
  br_4xs: 2,
  br_3xs: 3,
  br_2xs: 4,
  br_xs: 5,
  br_sm: 8,
  br_md: 10,
  br_lg: 12,
  br_xl: 14,
  br_2xl: 16,
  br_3xl: 20,
  br_4xl: 31,
};
